P1/urls.py
from django.contrib import admin
from django.urls import path,include
import myapp
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("myapp.urls")),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    
    

myapp/urls.py
from django.urls import path
from myapp import views

app_name='myapp'
urlpatterns = [
    path('',views.index,name='index'),
    path('multi_select/',views.multi_select,name="multi_select"),
    path('form_demo/',views.form_demo,name="form_demo"),
    path('disp_form/',views.disp_form,name='disp_form'),
    path('img_demo/',views.image_ip,name="img_demo"),
    path('form_val/',views.val_form,name='form_val'),
    path('img/',views.img_mod,name="img"),
    path('images/',views.img_db,name='img_db'),
    path('register/',views.register_user,name="register"),
    path('home/',views.homepage,name="home"),
    path(r'^login/$',views.user_login,name='login'),
    path('logout/',views.user_logout,name="logout"),
    path('sample/',views.sample,name="sample"),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
    <title>Base Page</title>
    {% endblock %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="nav">
        <a class="nav-link active" href="{% url 'myapp:home' %}">Home Page</a>
        
        {% if user.is_authenticated %}
        <a class="nav-link" href="{% url 'myapp:sample' %}">sample</a>
        <a class="nav-link" href="{% url 'myapp:logout' %}">Logout</a>
        {% else %}
        <a class="nav-link" href="{% url 'myapp:register' %}">Registration</a>
        <a class="nav-link" href="{% url 'myapp:login' %}">Login</a>

        {% endif %}
                
      </nav>
      <h1>Welcome to Homepage</h1>
    {% block content %}
    {% endblock %}
</body>
</html>

templates/disp_img.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <img src={{url_data}} alt="No image" found>
</body>
</html>

templates/form_demo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Form Demo</title>
</head>
<body>
    <h1>Fill The Form</h1>
    <form action="{% url 'myapp:disp_form' %}" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="submit">
    </form>
</body>
</html>

templates/html_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Form Demo</title>
</head>
<body>
    <h1>Fill The Form</h1>
    <form method="POST">
        {% csrf_token %}
        <label for="first_name">First Name</label>
        <input type="text" name="first_name" id="first_name" maxlength="20" minlength="3" required>
        <label for="last_name">Last Name</label>
        <input type="text" name="last_name" id="last_name" maxlength="20" minlength="1" required>
        
    </form>
</body>
</html>

templates/img_db.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% if images %}
      {% for img in images %}
      <img src={{img.profile_pic.url}} alt="" height="100" width="70">
      <br>
      {% endfor %}
    {% else %}
      
    {% endif %}
    
</body>
</html>

templates/img_demo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>upload image</title>
</head>
<body>
    <h1>Image Demo Form</h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Submit">
    </form>
</body>
</html>

templates/multi_select.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>multi select</title>
</head>
<body>
    <h1>select multiple records</h1>
    <form method="POST">
        {% csrf_token %}
        <label for="multi">Fav Foods</label>
        <select name="multi" id="multi" multiple>
            <option value="Dosa">Dosa</option>
            <option value="Biryani">Biryani</option>
            <option value="Kabab">Kabab</option>
            <option value="Gobi">Gobi</option>
        </select><br>
        Idli<input type="checkbox" name="food" id="food" value="Idli"><br>
        Dosa<input type="checkbox" name="food" id="food" value="Dosa"><br>
        Poori<input type="checkbox" name="food" id="food" value="Poori"><br>
        Bajji<input type="checkbox" name="food" id="food" value="Bajji"><br>
        Coffee<input type="checkbox" name="food" id="food" value="coffee"><br>
        

        <input type="submit" value="submit">
    </form>

</body>
</html>

templates/sam_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Form Validation Demo</title>
</head>
<body>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Submit">
    </form>
</body>
</html>

templates/user_login.html
{% extends "base.html" %}

{% block title %}
  <title>Login Page</title>
{% endblock %}
{% block content %}
  <form method="POST">
      {% csrf_token %}
      <label for="email">Email</label>
      <input type="email" name="email" id="email">
      <label for="password">Password</label>
      <input type="password" name="password" id="password">
      <input type="submit" value="Login">
  </form>
{% endblock %}